version: '3.8'
services:
  api:
    image: backend-python-app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
      - hf_cache:/cache/huggingface
      - pip_cache:/cache/pip
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  hf_cache:
  pip_cache:
