version: '3.8'

services:
  primary:
    image: bitnami/postgresql:15
    container_name: primary
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl
      - POSTGRESQL_REPLICATION_PASSWORD=replpass
      - POSTGRESQL_USERNAME=youruser
      - POSTGRESQL_PASSWORD=yourpass
      - POSTGRESQL_DATABASE=assistant
      - POSTGRESQL_WAL_LEVEL=replica
      - POSTGRESQL_MAX_WAL_SENDERS=10
    volumes:
      - primary_data:/bitnami/postgresql
    networks:
      - pg-network

  replica1:
    image: bitnami/postgresql:15
    container_name: replica1
    depends_on:
      - primary
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl
      - POSTGRESQL_REPLICATION_PASSWORD=replpass
      - POSTGRESQL_MASTER_HOST=primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=youruser
      - POSTGRESQL_PASSWORD=yourpass
      - POSTGRESQL_DATABASE=assistant
    volumes:
      - replica1_data:/bitnami/postgresql
    networks:
      - pg-network

  replica2:
    image: bitnami/postgresql:15
    container_name: replica2
    depends_on:
      - primary
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl
      - POSTGRESQL_REPLICATION_PASSWORD=replpass
      - POSTGRESQL_MASTER_HOST=primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=youruser
      - POSTGRESQL_PASSWORD=yourpass
      - POSTGRESQL_DATABASE=assistant
    volumes:
      - replica2_data:/bitnami/postgresql
    networks:
      - pg-network

  redis:
    image: bitnami/redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - pg-network

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - pg-network

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - pg-network

  minio:
    image: minio/minio
    container_name: minio_assistant
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - pg-network

volumes:
  primary_data:
  replica1_data:
  replica2_data:
  minio_data:

networks:
  pg-network:
    driver: bridge
